version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 4000:4000
  db:
    image: postgres:9.6-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    