version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    environment:
      - PGUSER=user
      - PGPASSWORD=pass
      - PGDATABASE=rubens_banking_api_test
      - PGPORT=5432
      - PGHOST=db
      - MIX_ENV=test
    depends_on:
      - db
    ports:
      - 4000:4000
    command: "make db setup"
  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=rubens_banking_api_test
